// Auto-generated by scripts/process-images.mjs — do not edit manually
// Generated: 2026-03-15T13:20:14.896Z

export type ImageVariant = {
  thumb?: string;
  sm?: string;
  md?: string;
  lg?: string;
  xl?: string;
  og?: string;
};

export type ImageEntry = {
  category: string;
  width: number;
  height: number;
  variants: ImageVariant;
  avif: ImageVariant;
  og?: string;
};

export const STORAGE_BUCKET = 'urbanstyle-ltd.firebasestorage.app';
export const STORAGE_BASE = 'https://firebasestorage.googleapis.com/v0/b/urbanstyle-ltd.firebasestorage.app/o';

export function getImageUrl(path: string): string {
  return `${STORAGE_BASE}/${encodeURIComponent(path)}?alt=media`;
}

export const images: Record<string, ImageEntry> = {
  "anna_mets_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/anna_mets_ref_thumb.webp",
      "sm": "images/v1/personas/anna_mets_ref_sm.webp",
      "md": "images/v1/personas/anna_mets_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/anna_mets_ref_thumb.avif",
      "sm": "images/v1/personas/anna_mets_ref_sm.avif",
      "md": "images/v1/personas/anna_mets_ref_md.avif"
    },
    "og": "images/v1/personas/anna_mets_ref_og.png"
  },
  "kristi_tamm_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/kristi_tamm_ref_thumb.webp",
      "sm": "images/v1/personas/kristi_tamm_ref_sm.webp",
      "md": "images/v1/personas/kristi_tamm_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/kristi_tamm_ref_thumb.avif",
      "sm": "images/v1/personas/kristi_tamm_ref_sm.avif",
      "md": "images/v1/personas/kristi_tamm_ref_md.avif"
    },
    "og": "images/v1/personas/kristi_tamm_ref_og.png"
  },
  "liis_koppel_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/liis_koppel_ref_thumb.webp",
      "sm": "images/v1/personas/liis_koppel_ref_sm.webp",
      "md": "images/v1/personas/liis_koppel_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/liis_koppel_ref_thumb.avif",
      "sm": "images/v1/personas/liis_koppel_ref_sm.avif",
      "md": "images/v1/personas/liis_koppel_ref_md.avif"
    },
    "og": "images/v1/personas/liis_koppel_ref_og.png"
  },
  "marko_saar_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/marko_saar_ref_thumb.webp",
      "sm": "images/v1/personas/marko_saar_ref_sm.webp",
      "md": "images/v1/personas/marko_saar_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/marko_saar_ref_thumb.avif",
      "sm": "images/v1/personas/marko_saar_ref_sm.avif",
      "md": "images/v1/personas/marko_saar_ref_md.avif"
    },
    "og": "images/v1/personas/marko_saar_ref_og.png"
  },
  "toomas_kask_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/toomas_kask_ref_thumb.webp",
      "sm": "images/v1/personas/toomas_kask_ref_sm.webp",
      "md": "images/v1/personas/toomas_kask_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/toomas_kask_ref_thumb.avif",
      "sm": "images/v1/personas/toomas_kask_ref_sm.avif",
      "md": "images/v1/personas/toomas_kask_ref_md.avif"
    },
    "og": "images/v1/personas/toomas_kask_ref_og.png"
  },
  "product_1a_denim_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1a_denim_hero_thumb.webp",
      "sm": "images/v1/products/product_1a_denim_hero_sm.webp",
      "md": "images/v1/products/product_1a_denim_hero_md.webp",
      "lg": "images/v1/products/product_1a_denim_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1a_denim_hero_thumb.avif",
      "sm": "images/v1/products/product_1a_denim_hero_sm.avif",
      "md": "images/v1/products/product_1a_denim_hero_md.avif",
      "lg": "images/v1/products/product_1a_denim_hero_lg.avif"
    },
    "og": "images/v1/products/product_1a_denim_hero_og.png"
  },
  "product_1b_denim_back": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_back_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_back_sm.webp",
      "md": "images/v1/products/product_1b_denim_back_md.webp",
      "lg": "images/v1/products/product_1b_denim_back_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_back_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_back_sm.avif",
      "md": "images/v1/products/product_1b_denim_back_md.avif",
      "lg": "images/v1/products/product_1b_denim_back_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_back_og.png"
  },
  "product_1b_denim_button": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_button_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_button_sm.webp",
      "md": "images/v1/products/product_1b_denim_button_md.webp",
      "lg": "images/v1/products/product_1b_denim_button_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_button_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_button_sm.avif",
      "md": "images/v1/products/product_1b_denim_button_md.avif",
      "lg": "images/v1/products/product_1b_denim_button_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_button_og.png"
  },
  "product_1b_denim_lining": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_lining_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_lining_sm.webp",
      "md": "images/v1/products/product_1b_denim_lining_md.webp",
      "lg": "images/v1/products/product_1b_denim_lining_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_lining_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_lining_sm.avif",
      "md": "images/v1/products/product_1b_denim_lining_md.avif",
      "lg": "images/v1/products/product_1b_denim_lining_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_lining_og.png"
  },
  "product_1b_denim_stitch": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_stitch_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_stitch_sm.webp",
      "md": "images/v1/products/product_1b_denim_stitch_md.webp",
      "lg": "images/v1/products/product_1b_denim_stitch_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_stitch_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_stitch_sm.avif",
      "md": "images/v1/products/product_1b_denim_stitch_md.avif",
      "lg": "images/v1/products/product_1b_denim_stitch_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_stitch_og.png"
  },
  "product_1e_denim_flatlay": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1e_denim_flatlay_thumb.webp",
      "sm": "images/v1/products/product_1e_denim_flatlay_sm.webp",
      "md": "images/v1/products/product_1e_denim_flatlay_md.webp",
      "lg": "images/v1/products/product_1e_denim_flatlay_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1e_denim_flatlay_thumb.avif",
      "sm": "images/v1/products/product_1e_denim_flatlay_sm.avif",
      "md": "images/v1/products/product_1e_denim_flatlay_md.avif",
      "lg": "images/v1/products/product_1e_denim_flatlay_lg.avif"
    },
    "og": "images/v1/products/product_1e_denim_flatlay_og.png"
  },
  "product_2a_hoodie_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2a_hoodie_hero_thumb.webp",
      "sm": "images/v1/products/product_2a_hoodie_hero_sm.webp",
      "md": "images/v1/products/product_2a_hoodie_hero_md.webp",
      "lg": "images/v1/products/product_2a_hoodie_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2a_hoodie_hero_thumb.avif",
      "sm": "images/v1/products/product_2a_hoodie_hero_sm.avif",
      "md": "images/v1/products/product_2a_hoodie_hero_md.avif",
      "lg": "images/v1/products/product_2a_hoodie_hero_lg.avif"
    },
    "og": "images/v1/products/product_2a_hoodie_hero_og.png"
  },
  "product_2b_hoodie_colors": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2b_hoodie_colors_thumb.webp",
      "sm": "images/v1/products/product_2b_hoodie_colors_sm.webp",
      "md": "images/v1/products/product_2b_hoodie_colors_md.webp",
      "lg": "images/v1/products/product_2b_hoodie_colors_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2b_hoodie_colors_thumb.avif",
      "sm": "images/v1/products/product_2b_hoodie_colors_sm.avif",
      "md": "images/v1/products/product_2b_hoodie_colors_md.avif",
      "lg": "images/v1/products/product_2b_hoodie_colors_lg.avif"
    },
    "og": "images/v1/products/product_2b_hoodie_colors_og.png"
  },
  "product_2b_hoodie_embroidery": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2b_hoodie_embroidery_thumb.webp",
      "sm": "images/v1/products/product_2b_hoodie_embroidery_sm.webp",
      "md": "images/v1/products/product_2b_hoodie_embroidery_md.webp",
      "lg": "images/v1/products/product_2b_hoodie_embroidery_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2b_hoodie_embroidery_thumb.avif",
      "sm": "images/v1/products/product_2b_hoodie_embroidery_sm.avif",
      "md": "images/v1/products/product_2b_hoodie_embroidery_md.avif",
      "lg": "images/v1/products/product_2b_hoodie_embroidery_lg.avif"
    },
    "og": "images/v1/products/product_2b_hoodie_embroidery_og.png"
  },
  "product_2b_hoodie_fabric": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2b_hoodie_fabric_thumb.webp",
      "sm": "images/v1/products/product_2b_hoodie_fabric_sm.webp",
      "md": "images/v1/products/product_2b_hoodie_fabric_md.webp",
      "lg": "images/v1/products/product_2b_hoodie_fabric_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2b_hoodie_fabric_thumb.avif",
      "sm": "images/v1/products/product_2b_hoodie_fabric_sm.avif",
      "md": "images/v1/products/product_2b_hoodie_fabric_md.avif",
      "lg": "images/v1/products/product_2b_hoodie_fabric_lg.avif"
    },
    "og": "images/v1/products/product_2b_hoodie_fabric_og.png"
  },
  "product_3a_tee_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3a_tee_hero_thumb.webp",
      "sm": "images/v1/products/product_3a_tee_hero_sm.webp",
      "md": "images/v1/products/product_3a_tee_hero_md.webp",
      "lg": "images/v1/products/product_3a_tee_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3a_tee_hero_thumb.avif",
      "sm": "images/v1/products/product_3a_tee_hero_sm.avif",
      "md": "images/v1/products/product_3a_tee_hero_md.avif",
      "lg": "images/v1/products/product_3a_tee_hero_lg.avif"
    },
    "og": "images/v1/products/product_3a_tee_hero_og.png"
  },
  "product_3b_tee_design1": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design1_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design1_sm.webp",
      "md": "images/v1/products/product_3b_tee_design1_md.webp",
      "lg": "images/v1/products/product_3b_tee_design1_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design1_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design1_sm.avif",
      "md": "images/v1/products/product_3b_tee_design1_md.avif",
      "lg": "images/v1/products/product_3b_tee_design1_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design1_og.png"
  },
  "product_3b_tee_design2": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design2_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design2_sm.webp",
      "md": "images/v1/products/product_3b_tee_design2_md.webp",
      "lg": "images/v1/products/product_3b_tee_design2_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design2_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design2_sm.avif",
      "md": "images/v1/products/product_3b_tee_design2_md.avif",
      "lg": "images/v1/products/product_3b_tee_design2_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design2_og.png"
  },
  "product_3b_tee_design3": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design3_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design3_sm.webp",
      "md": "images/v1/products/product_3b_tee_design3_md.webp",
      "lg": "images/v1/products/product_3b_tee_design3_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design3_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design3_sm.avif",
      "md": "images/v1/products/product_3b_tee_design3_md.avif",
      "lg": "images/v1/products/product_3b_tee_design3_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design3_og.png"
  },
  "product_3b_tee_design4": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design4_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design4_sm.webp",
      "md": "images/v1/products/product_3b_tee_design4_md.webp",
      "lg": "images/v1/products/product_3b_tee_design4_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design4_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design4_sm.avif",
      "md": "images/v1/products/product_3b_tee_design4_md.avif",
      "lg": "images/v1/products/product_3b_tee_design4_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design4_og.png"
  },
  "product_4a_joggers_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_4a_joggers_hero_thumb.webp",
      "sm": "images/v1/products/product_4a_joggers_hero_sm.webp",
      "md": "images/v1/products/product_4a_joggers_hero_md.webp",
      "lg": "images/v1/products/product_4a_joggers_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_4a_joggers_hero_thumb.avif",
      "sm": "images/v1/products/product_4a_joggers_hero_sm.avif",
      "md": "images/v1/products/product_4a_joggers_hero_md.avif",
      "lg": "images/v1/products/product_4a_joggers_hero_lg.avif"
    },
    "og": "images/v1/products/product_4a_joggers_hero_og.png"
  },
  "product_4b_joggers_fabric": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_4b_joggers_fabric_thumb.webp",
      "sm": "images/v1/products/product_4b_joggers_fabric_sm.webp",
      "md": "images/v1/products/product_4b_joggers_fabric_md.webp",
      "lg": "images/v1/products/product_4b_joggers_fabric_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_4b_joggers_fabric_thumb.avif",
      "sm": "images/v1/products/product_4b_joggers_fabric_sm.avif",
      "md": "images/v1/products/product_4b_joggers_fabric_md.avif",
      "lg": "images/v1/products/product_4b_joggers_fabric_lg.avif"
    },
    "og": "images/v1/products/product_4b_joggers_fabric_og.png"
  },
  "product_4b_joggers_pocket": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_4b_joggers_pocket_thumb.webp",
      "sm": "images/v1/products/product_4b_joggers_pocket_sm.webp",
      "md": "images/v1/products/product_4b_joggers_pocket_md.webp",
      "lg": "images/v1/products/product_4b_joggers_pocket_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_4b_joggers_pocket_thumb.avif",
      "sm": "images/v1/products/product_4b_joggers_pocket_sm.avif",
      "md": "images/v1/products/product_4b_joggers_pocket_md.avif",
      "lg": "images/v1/products/product_4b_joggers_pocket_lg.avif"
    },
    "og": "images/v1/products/product_4b_joggers_pocket_og.png"
  },
  "product_5a_bag_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_5a_bag_hero_thumb.webp",
      "sm": "images/v1/products/product_5a_bag_hero_sm.webp",
      "md": "images/v1/products/product_5a_bag_hero_md.webp",
      "lg": "images/v1/products/product_5a_bag_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_5a_bag_hero_thumb.avif",
      "sm": "images/v1/products/product_5a_bag_hero_sm.avif",
      "md": "images/v1/products/product_5a_bag_hero_md.avif",
      "lg": "images/v1/products/product_5a_bag_hero_lg.avif"
    },
    "og": "images/v1/products/product_5a_bag_hero_og.png"
  },
  "product_6a_beanie_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_6a_beanie_hero_thumb.webp",
      "sm": "images/v1/products/product_6a_beanie_hero_sm.webp",
      "md": "images/v1/products/product_6a_beanie_hero_md.webp",
      "lg": "images/v1/products/product_6a_beanie_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_6a_beanie_hero_thumb.avif",
      "sm": "images/v1/products/product_6a_beanie_hero_sm.avif",
      "md": "images/v1/products/product_6a_beanie_hero_md.avif",
      "lg": "images/v1/products/product_6a_beanie_hero_lg.avif"
    },
    "og": "images/v1/products/product_6a_beanie_hero_og.png"
  },
  "product_6b_cap_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_6b_cap_hero_thumb.webp",
      "sm": "images/v1/products/product_6b_cap_hero_sm.webp",
      "md": "images/v1/products/product_6b_cap_hero_md.webp",
      "lg": "images/v1/products/product_6b_cap_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_6b_cap_hero_thumb.avif",
      "sm": "images/v1/products/product_6b_cap_hero_sm.avif",
      "md": "images/v1/products/product_6b_cap_hero_md.avif",
      "lg": "images/v1/products/product_6b_cap_hero_lg.avif"
    },
    "og": "images/v1/products/product_6b_cap_hero_og.png"
  },
  "product_6c_accessories_group": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_6c_accessories_group_thumb.webp",
      "sm": "images/v1/products/product_6c_accessories_group_sm.webp",
      "md": "images/v1/products/product_6c_accessories_group_md.webp",
      "lg": "images/v1/products/product_6c_accessories_group_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_6c_accessories_group_thumb.avif",
      "sm": "images/v1/products/product_6c_accessories_group_sm.avif",
      "md": "images/v1/products/product_6c_accessories_group_md.avif",
      "lg": "images/v1/products/product_6c_accessories_group_lg.avif"
    },
    "og": "images/v1/products/product_6c_accessories_group_og.png"
  },
  "product_7a_parka_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_7a_parka_hero_thumb.webp",
      "sm": "images/v1/products/product_7a_parka_hero_sm.webp",
      "md": "images/v1/products/product_7a_parka_hero_md.webp",
      "lg": "images/v1/products/product_7a_parka_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_7a_parka_hero_thumb.avif",
      "sm": "images/v1/products/product_7a_parka_hero_sm.avif",
      "md": "images/v1/products/product_7a_parka_hero_md.avif",
      "lg": "images/v1/products/product_7a_parka_hero_lg.avif"
    },
    "og": "images/v1/products/product_7a_parka_hero_og.png"
  },
  "product_7b_parka_hood": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_7b_parka_hood_thumb.webp",
      "sm": "images/v1/products/product_7b_parka_hood_sm.webp",
      "md": "images/v1/products/product_7b_parka_hood_md.webp",
      "lg": "images/v1/products/product_7b_parka_hood_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_7b_parka_hood_thumb.avif",
      "sm": "images/v1/products/product_7b_parka_hood_sm.avif",
      "md": "images/v1/products/product_7b_parka_hood_md.avif",
      "lg": "images/v1/products/product_7b_parka_hood_lg.avif"
    },
    "og": "images/v1/products/product_7b_parka_hood_og.png"
  },
  "product_7b_parka_seam": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_7b_parka_seam_thumb.webp",
      "sm": "images/v1/products/product_7b_parka_seam_sm.webp",
      "md": "images/v1/products/product_7b_parka_seam_md.webp",
      "lg": "images/v1/products/product_7b_parka_seam_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_7b_parka_seam_thumb.avif",
      "sm": "images/v1/products/product_7b_parka_seam_sm.avif",
      "md": "images/v1/products/product_7b_parka_seam_md.avif",
      "lg": "images/v1/products/product_7b_parka_seam_lg.avif"
    },
    "og": "images/v1/products/product_7b_parka_seam_og.png"
  },
  "product_8a_sneaker_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_8a_sneaker_hero_thumb.webp",
      "sm": "images/v1/products/product_8a_sneaker_hero_sm.webp",
      "md": "images/v1/products/product_8a_sneaker_hero_md.webp",
      "lg": "images/v1/products/product_8a_sneaker_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_8a_sneaker_hero_thumb.avif",
      "sm": "images/v1/products/product_8a_sneaker_hero_sm.avif",
      "md": "images/v1/products/product_8a_sneaker_hero_md.avif",
      "lg": "images/v1/products/product_8a_sneaker_hero_lg.avif"
    },
    "og": "images/v1/products/product_8a_sneaker_hero_og.png"
  }
} as const;
