// Auto-generated by scripts/process-images.mjs — do not edit manually
// Generated: 2026-03-15T20:31:45.105Z

export type ImageVariant = {
  thumb?: string;
  sm?: string;
  md?: string;
  lg?: string;
  xl?: string;
  og?: string;
};

export type ImageEntry = {
  category: string;
  width: number;
  height: number;
  variants: ImageVariant;
  avif: ImageVariant;
  og?: string;
};

export const STORAGE_BUCKET = 'urbanstyle-ltd.firebasestorage.app';
export const STORAGE_BASE = 'https://firebasestorage.googleapis.com/v0/b/urbanstyle-ltd.firebasestorage.app/o';

export function getImageUrl(path: string): string {
  return `${STORAGE_BASE}/${encodeURIComponent(path)}?alt=media`;
}

export const images: Record<string, ImageEntry> = {
  "hero_cityscape": {
    "category": "hero",
    "width": 640,
    "height": 640,
    "variants": {
      "md": "images/v1/hero/hero_cityscape_md.webp",
      "lg": "images/v1/hero/hero_cityscape_lg.webp",
      "xl": "images/v1/hero/hero_cityscape_xl.webp"
    },
    "avif": {
      "md": "images/v1/hero/hero_cityscape_md.avif",
      "lg": "images/v1/hero/hero_cityscape_lg.avif",
      "xl": "images/v1/hero/hero_cityscape_xl.avif"
    },
    "og": "images/v1/hero/hero_cityscape_og.png"
  },
  "hero_denim_season": {
    "category": "hero",
    "width": 640,
    "height": 640,
    "variants": {
      "md": "images/v1/hero/hero_denim_season_md.webp",
      "lg": "images/v1/hero/hero_denim_season_lg.webp",
      "xl": "images/v1/hero/hero_denim_season_xl.webp"
    },
    "avif": {
      "md": "images/v1/hero/hero_denim_season_md.avif",
      "lg": "images/v1/hero/hero_denim_season_lg.avif",
      "xl": "images/v1/hero/hero_denim_season_xl.avif"
    },
    "og": "images/v1/hero/hero_denim_season_og.png"
  },
  "hero_product_focus": {
    "category": "hero",
    "width": 640,
    "height": 640,
    "variants": {
      "md": "images/v1/hero/hero_product_focus_md.webp",
      "lg": "images/v1/hero/hero_product_focus_lg.webp",
      "xl": "images/v1/hero/hero_product_focus_xl.webp"
    },
    "avif": {
      "md": "images/v1/hero/hero_product_focus_md.avif",
      "lg": "images/v1/hero/hero_product_focus_lg.avif",
      "xl": "images/v1/hero/hero_product_focus_xl.avif"
    },
    "og": "images/v1/hero/hero_product_focus_og.png"
  },
  "hero_storm_ready": {
    "category": "hero",
    "width": 640,
    "height": 640,
    "variants": {
      "md": "images/v1/hero/hero_storm_ready_md.webp",
      "lg": "images/v1/hero/hero_storm_ready_lg.webp",
      "xl": "images/v1/hero/hero_storm_ready_xl.webp"
    },
    "avif": {
      "md": "images/v1/hero/hero_storm_ready_md.avif",
      "lg": "images/v1/hero/hero_storm_ready_lg.avif",
      "xl": "images/v1/hero/hero_storm_ready_xl.avif"
    },
    "og": "images/v1/hero/hero_storm_ready_og.png"
  },
  "team_group_hero": {
    "category": "hero",
    "width": 640,
    "height": 640,
    "variants": {
      "md": "images/v1/hero/team_group_hero_md.webp",
      "lg": "images/v1/hero/team_group_hero_lg.webp",
      "xl": "images/v1/hero/team_group_hero_xl.webp"
    },
    "avif": {
      "md": "images/v1/hero/team_group_hero_md.avif",
      "lg": "images/v1/hero/team_group_hero_lg.avif",
      "xl": "images/v1/hero/team_group_hero_xl.avif"
    },
    "og": "images/v1/hero/team_group_hero_og.png"
  },
  "anna_headshot": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/anna_headshot_thumb.webp",
      "sm": "images/v1/personas/anna_headshot_sm.webp",
      "md": "images/v1/personas/anna_headshot_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/anna_headshot_thumb.avif",
      "sm": "images/v1/personas/anna_headshot_sm.avif",
      "md": "images/v1/personas/anna_headshot_md.avif"
    },
    "og": "images/v1/personas/anna_headshot_og.png"
  },
  "anna_mets_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/anna_mets_ref_thumb.webp",
      "sm": "images/v1/personas/anna_mets_ref_sm.webp",
      "md": "images/v1/personas/anna_mets_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/anna_mets_ref_thumb.avif",
      "sm": "images/v1/personas/anna_mets_ref_sm.avif",
      "md": "images/v1/personas/anna_mets_ref_md.avif"
    },
    "og": "images/v1/personas/anna_mets_ref_og.png"
  },
  "kristi_headshot": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/kristi_headshot_thumb.webp",
      "sm": "images/v1/personas/kristi_headshot_sm.webp",
      "md": "images/v1/personas/kristi_headshot_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/kristi_headshot_thumb.avif",
      "sm": "images/v1/personas/kristi_headshot_sm.avif",
      "md": "images/v1/personas/kristi_headshot_md.avif"
    },
    "og": "images/v1/personas/kristi_headshot_og.png"
  },
  "kristi_tamm_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/kristi_tamm_ref_thumb.webp",
      "sm": "images/v1/personas/kristi_tamm_ref_sm.webp",
      "md": "images/v1/personas/kristi_tamm_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/kristi_tamm_ref_thumb.avif",
      "sm": "images/v1/personas/kristi_tamm_ref_sm.avif",
      "md": "images/v1/personas/kristi_tamm_ref_md.avif"
    },
    "og": "images/v1/personas/kristi_tamm_ref_og.png"
  },
  "liis_headshot": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/liis_headshot_thumb.webp",
      "sm": "images/v1/personas/liis_headshot_sm.webp",
      "md": "images/v1/personas/liis_headshot_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/liis_headshot_thumb.avif",
      "sm": "images/v1/personas/liis_headshot_sm.avif",
      "md": "images/v1/personas/liis_headshot_md.avif"
    },
    "og": "images/v1/personas/liis_headshot_og.png"
  },
  "liis_koppel_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/liis_koppel_ref_thumb.webp",
      "sm": "images/v1/personas/liis_koppel_ref_sm.webp",
      "md": "images/v1/personas/liis_koppel_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/liis_koppel_ref_thumb.avif",
      "sm": "images/v1/personas/liis_koppel_ref_sm.avif",
      "md": "images/v1/personas/liis_koppel_ref_md.avif"
    },
    "og": "images/v1/personas/liis_koppel_ref_og.png"
  },
  "marko_headshot": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/marko_headshot_thumb.webp",
      "sm": "images/v1/personas/marko_headshot_sm.webp",
      "md": "images/v1/personas/marko_headshot_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/marko_headshot_thumb.avif",
      "sm": "images/v1/personas/marko_headshot_sm.avif",
      "md": "images/v1/personas/marko_headshot_md.avif"
    },
    "og": "images/v1/personas/marko_headshot_og.png"
  },
  "marko_saar_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/marko_saar_ref_thumb.webp",
      "sm": "images/v1/personas/marko_saar_ref_sm.webp",
      "md": "images/v1/personas/marko_saar_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/marko_saar_ref_thumb.avif",
      "sm": "images/v1/personas/marko_saar_ref_sm.avif",
      "md": "images/v1/personas/marko_saar_ref_md.avif"
    },
    "og": "images/v1/personas/marko_saar_ref_og.png"
  },
  "toomas_headshot": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/toomas_headshot_thumb.webp",
      "sm": "images/v1/personas/toomas_headshot_sm.webp",
      "md": "images/v1/personas/toomas_headshot_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/toomas_headshot_thumb.avif",
      "sm": "images/v1/personas/toomas_headshot_sm.avif",
      "md": "images/v1/personas/toomas_headshot_md.avif"
    },
    "og": "images/v1/personas/toomas_headshot_og.png"
  },
  "toomas_kask_ref": {
    "category": "personas",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/personas/toomas_kask_ref_thumb.webp",
      "sm": "images/v1/personas/toomas_kask_ref_sm.webp",
      "md": "images/v1/personas/toomas_kask_ref_md.webp"
    },
    "avif": {
      "thumb": "images/v1/personas/toomas_kask_ref_thumb.avif",
      "sm": "images/v1/personas/toomas_kask_ref_sm.avif",
      "md": "images/v1/personas/toomas_kask_ref_md.avif"
    },
    "og": "images/v1/personas/toomas_kask_ref_og.png"
  },
  "product_1a_denim_card": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1a_denim_card_thumb.webp",
      "sm": "images/v1/products/product_1a_denim_card_sm.webp",
      "md": "images/v1/products/product_1a_denim_card_md.webp",
      "lg": "images/v1/products/product_1a_denim_card_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1a_denim_card_thumb.avif",
      "sm": "images/v1/products/product_1a_denim_card_sm.avif",
      "md": "images/v1/products/product_1a_denim_card_md.avif",
      "lg": "images/v1/products/product_1a_denim_card_lg.avif"
    },
    "og": "images/v1/products/product_1a_denim_card_og.png"
  },
  "product_1a_denim_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1a_denim_hero_thumb.webp",
      "sm": "images/v1/products/product_1a_denim_hero_sm.webp",
      "md": "images/v1/products/product_1a_denim_hero_md.webp",
      "lg": "images/v1/products/product_1a_denim_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1a_denim_hero_thumb.avif",
      "sm": "images/v1/products/product_1a_denim_hero_sm.avif",
      "md": "images/v1/products/product_1a_denim_hero_md.avif",
      "lg": "images/v1/products/product_1a_denim_hero_lg.avif"
    },
    "og": "images/v1/products/product_1a_denim_hero_og.png"
  },
  "product_1b_denim_back": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_back_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_back_sm.webp",
      "md": "images/v1/products/product_1b_denim_back_md.webp",
      "lg": "images/v1/products/product_1b_denim_back_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_back_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_back_sm.avif",
      "md": "images/v1/products/product_1b_denim_back_md.avif",
      "lg": "images/v1/products/product_1b_denim_back_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_back_og.png"
  },
  "product_1b_denim_button": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_button_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_button_sm.webp",
      "md": "images/v1/products/product_1b_denim_button_md.webp",
      "lg": "images/v1/products/product_1b_denim_button_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_button_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_button_sm.avif",
      "md": "images/v1/products/product_1b_denim_button_md.avif",
      "lg": "images/v1/products/product_1b_denim_button_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_button_og.png"
  },
  "product_1b_denim_lining": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_lining_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_lining_sm.webp",
      "md": "images/v1/products/product_1b_denim_lining_md.webp",
      "lg": "images/v1/products/product_1b_denim_lining_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_lining_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_lining_sm.avif",
      "md": "images/v1/products/product_1b_denim_lining_md.avif",
      "lg": "images/v1/products/product_1b_denim_lining_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_lining_og.png"
  },
  "product_1b_denim_stitch": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1b_denim_stitch_thumb.webp",
      "sm": "images/v1/products/product_1b_denim_stitch_sm.webp",
      "md": "images/v1/products/product_1b_denim_stitch_md.webp",
      "lg": "images/v1/products/product_1b_denim_stitch_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1b_denim_stitch_thumb.avif",
      "sm": "images/v1/products/product_1b_denim_stitch_sm.avif",
      "md": "images/v1/products/product_1b_denim_stitch_md.avif",
      "lg": "images/v1/products/product_1b_denim_stitch_lg.avif"
    },
    "og": "images/v1/products/product_1b_denim_stitch_og.png"
  },
  "product_1e_denim_flatlay": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_1e_denim_flatlay_thumb.webp",
      "sm": "images/v1/products/product_1e_denim_flatlay_sm.webp",
      "md": "images/v1/products/product_1e_denim_flatlay_md.webp",
      "lg": "images/v1/products/product_1e_denim_flatlay_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_1e_denim_flatlay_thumb.avif",
      "sm": "images/v1/products/product_1e_denim_flatlay_sm.avif",
      "md": "images/v1/products/product_1e_denim_flatlay_md.avif",
      "lg": "images/v1/products/product_1e_denim_flatlay_lg.avif"
    },
    "og": "images/v1/products/product_1e_denim_flatlay_og.png"
  },
  "product_2a_hoodie_card": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2a_hoodie_card_thumb.webp",
      "sm": "images/v1/products/product_2a_hoodie_card_sm.webp",
      "md": "images/v1/products/product_2a_hoodie_card_md.webp",
      "lg": "images/v1/products/product_2a_hoodie_card_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2a_hoodie_card_thumb.avif",
      "sm": "images/v1/products/product_2a_hoodie_card_sm.avif",
      "md": "images/v1/products/product_2a_hoodie_card_md.avif",
      "lg": "images/v1/products/product_2a_hoodie_card_lg.avif"
    },
    "og": "images/v1/products/product_2a_hoodie_card_og.png"
  },
  "product_2a_hoodie_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2a_hoodie_hero_thumb.webp",
      "sm": "images/v1/products/product_2a_hoodie_hero_sm.webp",
      "md": "images/v1/products/product_2a_hoodie_hero_md.webp",
      "lg": "images/v1/products/product_2a_hoodie_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2a_hoodie_hero_thumb.avif",
      "sm": "images/v1/products/product_2a_hoodie_hero_sm.avif",
      "md": "images/v1/products/product_2a_hoodie_hero_md.avif",
      "lg": "images/v1/products/product_2a_hoodie_hero_lg.avif"
    },
    "og": "images/v1/products/product_2a_hoodie_hero_og.png"
  },
  "product_2b_hoodie_colors": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2b_hoodie_colors_thumb.webp",
      "sm": "images/v1/products/product_2b_hoodie_colors_sm.webp",
      "md": "images/v1/products/product_2b_hoodie_colors_md.webp",
      "lg": "images/v1/products/product_2b_hoodie_colors_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2b_hoodie_colors_thumb.avif",
      "sm": "images/v1/products/product_2b_hoodie_colors_sm.avif",
      "md": "images/v1/products/product_2b_hoodie_colors_md.avif",
      "lg": "images/v1/products/product_2b_hoodie_colors_lg.avif"
    },
    "og": "images/v1/products/product_2b_hoodie_colors_og.png"
  },
  "product_2b_hoodie_embroidery": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2b_hoodie_embroidery_thumb.webp",
      "sm": "images/v1/products/product_2b_hoodie_embroidery_sm.webp",
      "md": "images/v1/products/product_2b_hoodie_embroidery_md.webp",
      "lg": "images/v1/products/product_2b_hoodie_embroidery_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2b_hoodie_embroidery_thumb.avif",
      "sm": "images/v1/products/product_2b_hoodie_embroidery_sm.avif",
      "md": "images/v1/products/product_2b_hoodie_embroidery_md.avif",
      "lg": "images/v1/products/product_2b_hoodie_embroidery_lg.avif"
    },
    "og": "images/v1/products/product_2b_hoodie_embroidery_og.png"
  },
  "product_2b_hoodie_fabric": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_2b_hoodie_fabric_thumb.webp",
      "sm": "images/v1/products/product_2b_hoodie_fabric_sm.webp",
      "md": "images/v1/products/product_2b_hoodie_fabric_md.webp",
      "lg": "images/v1/products/product_2b_hoodie_fabric_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_2b_hoodie_fabric_thumb.avif",
      "sm": "images/v1/products/product_2b_hoodie_fabric_sm.avif",
      "md": "images/v1/products/product_2b_hoodie_fabric_md.avif",
      "lg": "images/v1/products/product_2b_hoodie_fabric_lg.avif"
    },
    "og": "images/v1/products/product_2b_hoodie_fabric_og.png"
  },
  "product_3a_tee_card": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3a_tee_card_thumb.webp",
      "sm": "images/v1/products/product_3a_tee_card_sm.webp",
      "md": "images/v1/products/product_3a_tee_card_md.webp",
      "lg": "images/v1/products/product_3a_tee_card_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3a_tee_card_thumb.avif",
      "sm": "images/v1/products/product_3a_tee_card_sm.avif",
      "md": "images/v1/products/product_3a_tee_card_md.avif",
      "lg": "images/v1/products/product_3a_tee_card_lg.avif"
    },
    "og": "images/v1/products/product_3a_tee_card_og.png"
  },
  "product_3a_tee_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3a_tee_hero_thumb.webp",
      "sm": "images/v1/products/product_3a_tee_hero_sm.webp",
      "md": "images/v1/products/product_3a_tee_hero_md.webp",
      "lg": "images/v1/products/product_3a_tee_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3a_tee_hero_thumb.avif",
      "sm": "images/v1/products/product_3a_tee_hero_sm.avif",
      "md": "images/v1/products/product_3a_tee_hero_md.avif",
      "lg": "images/v1/products/product_3a_tee_hero_lg.avif"
    },
    "og": "images/v1/products/product_3a_tee_hero_og.png"
  },
  "product_3b_tee_design1": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design1_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design1_sm.webp",
      "md": "images/v1/products/product_3b_tee_design1_md.webp",
      "lg": "images/v1/products/product_3b_tee_design1_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design1_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design1_sm.avif",
      "md": "images/v1/products/product_3b_tee_design1_md.avif",
      "lg": "images/v1/products/product_3b_tee_design1_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design1_og.png"
  },
  "product_3b_tee_design2": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design2_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design2_sm.webp",
      "md": "images/v1/products/product_3b_tee_design2_md.webp",
      "lg": "images/v1/products/product_3b_tee_design2_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design2_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design2_sm.avif",
      "md": "images/v1/products/product_3b_tee_design2_md.avif",
      "lg": "images/v1/products/product_3b_tee_design2_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design2_og.png"
  },
  "product_3b_tee_design3": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design3_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design3_sm.webp",
      "md": "images/v1/products/product_3b_tee_design3_md.webp",
      "lg": "images/v1/products/product_3b_tee_design3_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design3_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design3_sm.avif",
      "md": "images/v1/products/product_3b_tee_design3_md.avif",
      "lg": "images/v1/products/product_3b_tee_design3_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design3_og.png"
  },
  "product_3b_tee_design4": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_3b_tee_design4_thumb.webp",
      "sm": "images/v1/products/product_3b_tee_design4_sm.webp",
      "md": "images/v1/products/product_3b_tee_design4_md.webp",
      "lg": "images/v1/products/product_3b_tee_design4_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_3b_tee_design4_thumb.avif",
      "sm": "images/v1/products/product_3b_tee_design4_sm.avif",
      "md": "images/v1/products/product_3b_tee_design4_md.avif",
      "lg": "images/v1/products/product_3b_tee_design4_lg.avif"
    },
    "og": "images/v1/products/product_3b_tee_design4_og.png"
  },
  "product_4a_joggers_card": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_4a_joggers_card_thumb.webp",
      "sm": "images/v1/products/product_4a_joggers_card_sm.webp",
      "md": "images/v1/products/product_4a_joggers_card_md.webp",
      "lg": "images/v1/products/product_4a_joggers_card_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_4a_joggers_card_thumb.avif",
      "sm": "images/v1/products/product_4a_joggers_card_sm.avif",
      "md": "images/v1/products/product_4a_joggers_card_md.avif",
      "lg": "images/v1/products/product_4a_joggers_card_lg.avif"
    },
    "og": "images/v1/products/product_4a_joggers_card_og.png"
  },
  "product_4a_joggers_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_4a_joggers_hero_thumb.webp",
      "sm": "images/v1/products/product_4a_joggers_hero_sm.webp",
      "md": "images/v1/products/product_4a_joggers_hero_md.webp",
      "lg": "images/v1/products/product_4a_joggers_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_4a_joggers_hero_thumb.avif",
      "sm": "images/v1/products/product_4a_joggers_hero_sm.avif",
      "md": "images/v1/products/product_4a_joggers_hero_md.avif",
      "lg": "images/v1/products/product_4a_joggers_hero_lg.avif"
    },
    "og": "images/v1/products/product_4a_joggers_hero_og.png"
  },
  "product_4b_joggers_fabric": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_4b_joggers_fabric_thumb.webp",
      "sm": "images/v1/products/product_4b_joggers_fabric_sm.webp",
      "md": "images/v1/products/product_4b_joggers_fabric_md.webp",
      "lg": "images/v1/products/product_4b_joggers_fabric_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_4b_joggers_fabric_thumb.avif",
      "sm": "images/v1/products/product_4b_joggers_fabric_sm.avif",
      "md": "images/v1/products/product_4b_joggers_fabric_md.avif",
      "lg": "images/v1/products/product_4b_joggers_fabric_lg.avif"
    },
    "og": "images/v1/products/product_4b_joggers_fabric_og.png"
  },
  "product_4b_joggers_pocket": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_4b_joggers_pocket_thumb.webp",
      "sm": "images/v1/products/product_4b_joggers_pocket_sm.webp",
      "md": "images/v1/products/product_4b_joggers_pocket_md.webp",
      "lg": "images/v1/products/product_4b_joggers_pocket_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_4b_joggers_pocket_thumb.avif",
      "sm": "images/v1/products/product_4b_joggers_pocket_sm.avif",
      "md": "images/v1/products/product_4b_joggers_pocket_md.avif",
      "lg": "images/v1/products/product_4b_joggers_pocket_lg.avif"
    },
    "og": "images/v1/products/product_4b_joggers_pocket_og.png"
  },
  "product_5a_bag_card": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_5a_bag_card_thumb.webp",
      "sm": "images/v1/products/product_5a_bag_card_sm.webp",
      "md": "images/v1/products/product_5a_bag_card_md.webp",
      "lg": "images/v1/products/product_5a_bag_card_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_5a_bag_card_thumb.avif",
      "sm": "images/v1/products/product_5a_bag_card_sm.avif",
      "md": "images/v1/products/product_5a_bag_card_md.avif",
      "lg": "images/v1/products/product_5a_bag_card_lg.avif"
    },
    "og": "images/v1/products/product_5a_bag_card_og.png"
  },
  "product_5a_bag_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_5a_bag_hero_thumb.webp",
      "sm": "images/v1/products/product_5a_bag_hero_sm.webp",
      "md": "images/v1/products/product_5a_bag_hero_md.webp",
      "lg": "images/v1/products/product_5a_bag_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_5a_bag_hero_thumb.avif",
      "sm": "images/v1/products/product_5a_bag_hero_sm.avif",
      "md": "images/v1/products/product_5a_bag_hero_md.avif",
      "lg": "images/v1/products/product_5a_bag_hero_lg.avif"
    },
    "og": "images/v1/products/product_5a_bag_hero_og.png"
  },
  "product_6a_beanie_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_6a_beanie_hero_thumb.webp",
      "sm": "images/v1/products/product_6a_beanie_hero_sm.webp",
      "md": "images/v1/products/product_6a_beanie_hero_md.webp",
      "lg": "images/v1/products/product_6a_beanie_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_6a_beanie_hero_thumb.avif",
      "sm": "images/v1/products/product_6a_beanie_hero_sm.avif",
      "md": "images/v1/products/product_6a_beanie_hero_md.avif",
      "lg": "images/v1/products/product_6a_beanie_hero_lg.avif"
    },
    "og": "images/v1/products/product_6a_beanie_hero_og.png"
  },
  "product_6b_cap_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_6b_cap_hero_thumb.webp",
      "sm": "images/v1/products/product_6b_cap_hero_sm.webp",
      "md": "images/v1/products/product_6b_cap_hero_md.webp",
      "lg": "images/v1/products/product_6b_cap_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_6b_cap_hero_thumb.avif",
      "sm": "images/v1/products/product_6b_cap_hero_sm.avif",
      "md": "images/v1/products/product_6b_cap_hero_md.avif",
      "lg": "images/v1/products/product_6b_cap_hero_lg.avif"
    },
    "og": "images/v1/products/product_6b_cap_hero_og.png"
  },
  "product_6c_accessories_group": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_6c_accessories_group_thumb.webp",
      "sm": "images/v1/products/product_6c_accessories_group_sm.webp",
      "md": "images/v1/products/product_6c_accessories_group_md.webp",
      "lg": "images/v1/products/product_6c_accessories_group_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_6c_accessories_group_thumb.avif",
      "sm": "images/v1/products/product_6c_accessories_group_sm.avif",
      "md": "images/v1/products/product_6c_accessories_group_md.avif",
      "lg": "images/v1/products/product_6c_accessories_group_lg.avif"
    },
    "og": "images/v1/products/product_6c_accessories_group_og.png"
  },
  "product_7a_parka_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_7a_parka_hero_thumb.webp",
      "sm": "images/v1/products/product_7a_parka_hero_sm.webp",
      "md": "images/v1/products/product_7a_parka_hero_md.webp",
      "lg": "images/v1/products/product_7a_parka_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_7a_parka_hero_thumb.avif",
      "sm": "images/v1/products/product_7a_parka_hero_sm.avif",
      "md": "images/v1/products/product_7a_parka_hero_md.avif",
      "lg": "images/v1/products/product_7a_parka_hero_lg.avif"
    },
    "og": "images/v1/products/product_7a_parka_hero_og.png"
  },
  "product_7b_parka_hood": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_7b_parka_hood_thumb.webp",
      "sm": "images/v1/products/product_7b_parka_hood_sm.webp",
      "md": "images/v1/products/product_7b_parka_hood_md.webp",
      "lg": "images/v1/products/product_7b_parka_hood_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_7b_parka_hood_thumb.avif",
      "sm": "images/v1/products/product_7b_parka_hood_sm.avif",
      "md": "images/v1/products/product_7b_parka_hood_md.avif",
      "lg": "images/v1/products/product_7b_parka_hood_lg.avif"
    },
    "og": "images/v1/products/product_7b_parka_hood_og.png"
  },
  "product_7b_parka_seam": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_7b_parka_seam_thumb.webp",
      "sm": "images/v1/products/product_7b_parka_seam_sm.webp",
      "md": "images/v1/products/product_7b_parka_seam_md.webp",
      "lg": "images/v1/products/product_7b_parka_seam_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_7b_parka_seam_thumb.avif",
      "sm": "images/v1/products/product_7b_parka_seam_sm.avif",
      "md": "images/v1/products/product_7b_parka_seam_md.avif",
      "lg": "images/v1/products/product_7b_parka_seam_lg.avif"
    },
    "og": "images/v1/products/product_7b_parka_seam_og.png"
  },
  "product_8a_sneaker_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_8a_sneaker_hero_thumb.webp",
      "sm": "images/v1/products/product_8a_sneaker_hero_sm.webp",
      "md": "images/v1/products/product_8a_sneaker_hero_md.webp",
      "lg": "images/v1/products/product_8a_sneaker_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_8a_sneaker_hero_thumb.avif",
      "sm": "images/v1/products/product_8a_sneaker_hero_sm.avif",
      "md": "images/v1/products/product_8a_sneaker_hero_md.avif",
      "lg": "images/v1/products/product_8a_sneaker_hero_lg.avif"
    },
    "og": "images/v1/products/product_8a_sneaker_hero_og.png"
  },
  "product_accessories_flatlay": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_accessories_flatlay_thumb.webp",
      "sm": "images/v1/products/product_accessories_flatlay_sm.webp",
      "md": "images/v1/products/product_accessories_flatlay_md.webp",
      "lg": "images/v1/products/product_accessories_flatlay_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_accessories_flatlay_thumb.avif",
      "sm": "images/v1/products/product_accessories_flatlay_sm.avif",
      "md": "images/v1/products/product_accessories_flatlay_md.avif",
      "lg": "images/v1/products/product_accessories_flatlay_lg.avif"
    },
    "og": "images/v1/products/product_accessories_flatlay_og.png"
  },
  "product_beanie_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_beanie_hero_thumb.webp",
      "sm": "images/v1/products/product_beanie_hero_sm.webp",
      "md": "images/v1/products/product_beanie_hero_md.webp",
      "lg": "images/v1/products/product_beanie_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_beanie_hero_thumb.avif",
      "sm": "images/v1/products/product_beanie_hero_sm.avif",
      "md": "images/v1/products/product_beanie_hero_md.avif",
      "lg": "images/v1/products/product_beanie_hero_lg.avif"
    },
    "og": "images/v1/products/product_beanie_hero_og.png"
  },
  "product_cap_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_cap_hero_thumb.webp",
      "sm": "images/v1/products/product_cap_hero_sm.webp",
      "md": "images/v1/products/product_cap_hero_md.webp",
      "lg": "images/v1/products/product_cap_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_cap_hero_thumb.avif",
      "sm": "images/v1/products/product_cap_hero_sm.avif",
      "md": "images/v1/products/product_cap_hero_md.avif",
      "lg": "images/v1/products/product_cap_hero_lg.avif"
    },
    "og": "images/v1/products/product_cap_hero_og.png"
  },
  "product_parka_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_parka_hero_thumb.webp",
      "sm": "images/v1/products/product_parka_hero_sm.webp",
      "md": "images/v1/products/product_parka_hero_md.webp",
      "lg": "images/v1/products/product_parka_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_parka_hero_thumb.avif",
      "sm": "images/v1/products/product_parka_hero_sm.avif",
      "md": "images/v1/products/product_parka_hero_md.avif",
      "lg": "images/v1/products/product_parka_hero_lg.avif"
    },
    "og": "images/v1/products/product_parka_hero_og.png"
  },
  "product_parka_hood": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_parka_hood_thumb.webp",
      "sm": "images/v1/products/product_parka_hood_sm.webp",
      "md": "images/v1/products/product_parka_hood_md.webp",
      "lg": "images/v1/products/product_parka_hood_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_parka_hood_thumb.avif",
      "sm": "images/v1/products/product_parka_hood_sm.avif",
      "md": "images/v1/products/product_parka_hood_md.avif",
      "lg": "images/v1/products/product_parka_hood_lg.avif"
    },
    "og": "images/v1/products/product_parka_hood_og.png"
  },
  "product_parka_seam": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_parka_seam_thumb.webp",
      "sm": "images/v1/products/product_parka_seam_sm.webp",
      "md": "images/v1/products/product_parka_seam_md.webp",
      "lg": "images/v1/products/product_parka_seam_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_parka_seam_thumb.avif",
      "sm": "images/v1/products/product_parka_seam_sm.avif",
      "md": "images/v1/products/product_parka_seam_md.avif",
      "lg": "images/v1/products/product_parka_seam_lg.avif"
    },
    "og": "images/v1/products/product_parka_seam_og.png"
  },
  "product_sneaker_heel": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_sneaker_heel_thumb.webp",
      "sm": "images/v1/products/product_sneaker_heel_sm.webp",
      "md": "images/v1/products/product_sneaker_heel_md.webp",
      "lg": "images/v1/products/product_sneaker_heel_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_sneaker_heel_thumb.avif",
      "sm": "images/v1/products/product_sneaker_heel_sm.avif",
      "md": "images/v1/products/product_sneaker_heel_md.avif",
      "lg": "images/v1/products/product_sneaker_heel_lg.avif"
    },
    "og": "images/v1/products/product_sneaker_heel_og.png"
  },
  "product_sneaker_hero": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_sneaker_hero_thumb.webp",
      "sm": "images/v1/products/product_sneaker_hero_sm.webp",
      "md": "images/v1/products/product_sneaker_hero_md.webp",
      "lg": "images/v1/products/product_sneaker_hero_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_sneaker_hero_thumb.avif",
      "sm": "images/v1/products/product_sneaker_hero_sm.avif",
      "md": "images/v1/products/product_sneaker_hero_md.avif",
      "lg": "images/v1/products/product_sneaker_hero_lg.avif"
    },
    "og": "images/v1/products/product_sneaker_hero_og.png"
  },
  "product_sneaker_sole": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/product_sneaker_sole_thumb.webp",
      "sm": "images/v1/products/product_sneaker_sole_sm.webp",
      "md": "images/v1/products/product_sneaker_sole_md.webp",
      "lg": "images/v1/products/product_sneaker_sole_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/product_sneaker_sole_thumb.avif",
      "sm": "images/v1/products/product_sneaker_sole_sm.avif",
      "md": "images/v1/products/product_sneaker_sole_md.avif",
      "lg": "images/v1/products/product_sneaker_sole_lg.avif"
    },
    "og": "images/v1/products/product_sneaker_sole_og.png"
  },
  "strip_texture_montage": {
    "category": "products",
    "width": 640,
    "height": 640,
    "variants": {
      "thumb": "images/v1/products/strip_texture_montage_thumb.webp",
      "sm": "images/v1/products/strip_texture_montage_sm.webp",
      "md": "images/v1/products/strip_texture_montage_md.webp",
      "lg": "images/v1/products/strip_texture_montage_lg.webp"
    },
    "avif": {
      "thumb": "images/v1/products/strip_texture_montage_thumb.avif",
      "sm": "images/v1/products/strip_texture_montage_sm.avif",
      "md": "images/v1/products/strip_texture_montage_md.avif",
      "lg": "images/v1/products/strip_texture_montage_lg.avif"
    },
    "og": "images/v1/products/strip_texture_montage_og.png"
  }
} as const;
